import Head from 'next/head'
import { useRouter } from 'next/router'
import useSWR from 'swr'
import Title from '../../components/Title'
import LocationForm from '../../components/LocationForm'

const Location = () => {
  const router = useRouter()
  const { id } = router.query

  const fetcher = (url, queryParams = '?limit=100') =>
    fetch(`${url}${queryParams}`).then((res) => res.json())

  const { data, error, mutate } = useSWR(`/api/locations/${id}`, fetcher)

  if (!data) {
    return <div>Loading</div>
  } else {
    data.data.id = data.id
  }

  return (
    <div>
      <Head>
        <title>{data?.data?.locationName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto mt-10">
        <Title text={data?.data?.locationName} />
        <LocationForm location={data?.data} />
      </main>

      <footer></footer>
    </div>
  )
}

export default Location
