// import { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Table from '../components/Table'
import Button from '../components/Button'
import Title from '../components/Title'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Mitten Print Distribution</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-4 pt-6 mx-auto">
        <Title text={'All Publications'} />
        <Table publication />
        <Button label="Add Publication" link="/new-publication" />
        <Title text={'All Locations'} />
        <Button label="Add Location" link="/new-location" />
        <Table />
      </main>
    </div>
  )
}

export default Home

