// import { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Table from '../components/Table'
import Button from '../components/Button'
import Title from '../components/Title'
import { useSession, signIn, signOut } from "next-auth/react"
import PublisherTable from '../components/PublisherTable'


const Home = () => {
  const { data: session } = useSession()

  return (
    <div>
      <Head>
        <title>Mitten Print Distribution</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-4 pt-6 mx-auto">
      {(session?.user.role === undefined) ? (
          <Title text={'You must be signed in to access this data'} />
        ) : (() => {
          switch (session?.user.role) {
            case 'admin':
            return (
              <>
                <Title text={'All Publications'} />
                <Table publication />
                <Button label="Add Publication" link="/new-publication" />
                <Title text={'All Locations'} />
                <Button label="Add Location" link="/new-location" />
                <Table />
              </>
            )
            case 'pub':
            return (
              <>
                <Title text={'REVUE Locations'} />
                <PublisherTable />
              </>
            )
            default:
            return (
              <Title text={'You must be signed in to a priviledged user account access this data'} />
            )
          }
        })()}
      </main>
    </div>
  )
}

export default Home

